---
resources:
  - name: docker-image
    type: registry-image
    source:
      repository: golang
      tag: 1.17
      username: ((docker.username))
      password: ((docker.password))
  - name: socks5-proxy
    type: git
    source:
      branch: main
      uri: git@github.com:cloudfoundry/socks5-proxy.git
      private_key: ((github_deploy_key_socks5_proxy.private_key))
  - name: golang-release
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git
  - name: weekly
    type: time
    source:
      start: 1:00
      stop: 1:30
      days: [ Saturday ]
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:cloudfoundry/socks5-proxy.git
      branch: version
      file: version
      private_key: ((github_deploy_key_socks5_proxy.private_key))

jobs:
  - name: unit-tests
    plan:
      - in_parallel:
          - get: socks5-proxy
            trigger: true
          - get: docker-image
      - task: test-unit
        file: socks5-proxy/ci/tasks/test-unit.yml
        image: docker-image

  - name: bump-deps
    serial: true
    plan:
      - in_parallel:
          - get: weekly
            trigger: true
          - get: socks5-proxy
          - get: golang-release
          - get: docker-image
      - task: bump-deps
        file: golang-release/ci/tasks/shared/bump-deps.yml
        input_mapping:
          input_repo: socks5-proxy
        output_mapping:
          output_repo: bumped-socks5-proxy
      - task: test-unit
        file: socks5-proxy/ci/tasks/test-unit.yml
        image: docker-image
        input_mapping:
          socks5-proxy: bumped-socks5-proxy
      - put: socks5-proxy
        params:
          repository: bumped-socks5-proxy
          rebase: true
  - name: release-patch
    serial: true
    plan:
      - get: socks5-proxy
        passed:
          - bump-deps
        trigger: true
      - get: version
        params:
          bump: patch
      - put: version
        params:
          file: version/version
      - put: socks5-proxy
        params:
          only_tag: true
          repository: socks5-proxy
          tag: version/version
          tag_prefix: v
