---
name: go
on: [push, pull_request]
jobs:
  lint: # <- name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v8

  test-unit: # <- name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: go run github.com/onsi/ginkgo/v2/ginkgo run -r --keep-going ./...
